version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: forum-mysql
    environment:
      MYSQL_DATABASE: forum_api
      MYSQL_ROOT_PASSWORD: Notebook83
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - forum-network
    restart: unless-stopped

  forum-api:
    build: .
    container_name: forum-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/forum_api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Notebook83
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
      - forum-network

volumes:
  mysql_data:

networks:
  forum-network:
