version: '3.8'

services:
  forum-api:
    build: .
    container_name: forum-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://quorumify-db.cyfweoq4qoj2.us-east-1.rds.amazonaws.com:3306/quorumify
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: randompassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
      - forum-network

networks:
  forum-network:

