name: Docker Push & Build pipeline

on:
 push:
  branches:
   - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        uses: docker build -t ${{ secrets.DOCKER_USERNAME }}/quorumify:latest .

      - name: Push to DockerHub
        uses: docker push ${{ secrets.DOCKER_USERNAME }}/quorumify:latest







       
